# Generated by Django 4.2.24 on 2025-10-02 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'Pie Chart'), ('bar', 'Bar Chart'), ('doughnut', 'Doughnut Chart'), ('line', 'Line Chart'), ('radar', 'Radar Chart'), ('polarArea', 'Polar Area Chart')], default='pie', max_length=20),
        ),
        migrations.AddField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
