# Generated by Django 4.2.24 on 2025-10-02 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0002_statistic_chart_type_statistic_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this KPI is visible to all users'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created this KPI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
    ]
