# Generated by Django 4.2.24 on 2025-10-07 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0006_dataitem_timestamp_statistic_custom_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag. Inactive items are hidden from lists.'),
        ),
        migrations.CreateModel(
            name='KpiDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='stats.statistic')),
            ],
        ),
    ]
